language: rust
sudo: false

matrix:
  include:
    - os: osx
    - rust: stable
    - rust: beta
    - rust: nightly
      script: cargo bench --all
    - rust: nightly
      before_script:
        - pip install ghp-import --user && export PATH=$HOME/.local/bin:$PATH
      script:
        - cargo doc
      after_success:
        - ghp-import -n target/doc
        - git push -qf https://${GH_TOKEN}@github.com/${TRAVIS_REPO_SLUG}.git gh-pages
    - rust: stable
      script:
        - cargo build --manifest-path futures-core/Cargo.toml --no-default-features
        - cargo build --manifest-path futures/Cargo.toml --no-default-features
        - cargo build --manifest-path futures-channel/Cargo.toml --no-default-features
        - cargo build --manifest-path futures-executor/Cargo.toml --no-default-features
        - cargo build --manifest-path futures-sink/Cargo.toml --no-default-features
        - cargo build --manifest-path futures-util/Cargo.toml --no-default-features
    - rust: nightly
      script:
        - cargo build --manifest-path futures-core/Cargo.toml --features nightly
        - cargo build --manifest-path futures-stable/Cargo.toml --features nightly
        - cargo build --manifest-path futures-async-runtime/Cargo.toml --features nightly
        - cargo build --manifest-path futures-macro-async/Cargo.toml --features nightly
        - cargo build --manifest-path futures/Cargo.toml --features nightly
        - cargo test --manifest-path futures/Cargo.toml --features nightly --test async_await_tests
    - rust: 1.20.0
      script: cargo test --all
    - rust: nightly
      script:
        - cargo test --manifest-path futures/testcrate/Cargo.toml

script:
  - cargo test --all
  - cargo test --all --release

env:
  global:
    - secure: "iwVcMVIF7ZSY82fK5UyyUvVvJxMSYrbZawh1+4Oi8pvOdYq1gptcDoOC8jxWwCwrNF1b+/85n+jlEUngEqqSmV5PjAbWPjoc+u4Zn7CRi1AlxoUlvHPiQm4vM4Mkkd6GsqoIZttCeedU9m/w0nQ18uUtK8uD6vr2FVdcMnUnkYQAxuGOowGLrwidukzfBXMCu/JrwKMIbt61knAFiI/KJknu0h1mRrhpeF/sQ3tJFzRRcQeFJkbfwDzltMpPo1hq5D3HI4ONjYi/qO2pwUhDk4umfp9cLW9MS8rQvptxJTQmWemHi+f2/U4ld6a0URL6kEuMkt/EbH0A74eFtlicfRs44dX9MlWoqbLypnC3ymqmHcpwcwNA3HmZyg800MTuU+BPK41HIPdO9tPpxjHEiqvNDknH7qs+YBnis0eH7DHJgEjXq651PjW7pm+rnHPwsj+OzKE1YBNxBQZZDkS3VnZJz+O4tVsOzc3IOz0e+lf7VVuI17C9haj117nKp3umC4MVBA0S8RfreFgqpyDeY2zwcqOr0YOlEGGRl0vyWP8Qcxx12kQ7+doLolt6Kxda4uO0hKRmIF6+qki1T+L7v8BOGOtCncz4f7IX48eQ7+Wu0OtglRn45qAa3CxjUuW6xX3KSNH66PCXV0Jtp8Ga2SSevX2wtbbFu9f+9R+PQY4="

notifications:
  email:
    on_success: never
