[workspace]
members = [
  "futures",
  "futures-async-runtime",
  "futures-core",
  "futures-channel",
  "futures-executor",
  "futures-io",
  "futures-macro-async",
  "futures-macro-await",
  "futures-sink",
  "futures-stable",
  "futures-util",
]
