[package]
name = "md2"
version = "0.7.0"
authors = ["RustCrypto Developers"]
license = "MIT/Apache-2.0"
description = "MD2 hash function"
documentation = "https://docs.rs/md2"
repository = "https://github.com/RustCrypto/hashes"
keywords = ["crypto", "md2", "hash", "digest"]
categories = ["cryptography", "no-std"]

[dependencies]
digest = "0.7"
block-buffer = "0.3"

[dev-dependencies]
digest = { version = "^0.7.1", features = ["dev"] }

[badges]
travis-ci = { repository = "RustCrypto/hashes" }
