[package]
name = "des"
version = "0.1.0"
authors = ["RustCrypto Developers"]
license = "MIT/Apache-2.0"
description = "DES and Triple DES (3DES, TDES) block ciphers implementation"
documentation = "https://docs.rs/des"
repository = "https://github.com/RustCrypto/block-ciphers"
keywords = ["crypto", "des", "tdes", "block-cipher"]
categories = ["cryptography", "no-std"]

[dependencies]
block-cipher-trait = "0.5"
byte-tools = "0.2"
opaque-debug = "0.1"

[dev-dependencies]
block-cipher-trait = { version = "0.5", features = ["dev"] }

[badges]
travis-ci = { repository = "RustCrypto/block-ciphers" }
