[package]
name = "gost94"
version = "0.7.0"
authors = ["RustCrypto Developers"]
license = "MIT/Apache-2.0"
description = "GOST R 34.11-94 hash function"
documentation = "https://docs.rs/gost94"
repository = "https://github.com/RustCrypto/hashes"
keywords = ["crypto", "gost94", "gost", "hash", "digest"]
categories = ["cryptography", "no-std"]

[dependencies]
digest = "0.7"
byte-tools = "0.2"
block-buffer = "0.3"

[dev-dependencies]
digest = { version = "^0.7.1", features = ["dev"] }

[badges]
travis-ci = { repository = "RustCrypto/hashes" }
