name: genact
version: '0.4.0~git'
summary: a nonsense activity generator
description: |
  Pretend to be busy or waiting for your computer when you should
  actually be doing real work! Impress people with your insane
  multitasking skills. Just open a few instances of genact and watch
  the show. genact has multiple scenes that pretend to be doing
  something exciting or useful when in reality nothing is
  happening at all.

grade: stable
confinement: strict

apps:
  genact:
    command: bin/genact
    aliases:
      - genact

parts:
  genact:
    plugin: rust
    source: https://github.com/svenstaro/genact.git
