version: 2

jobs:
  build:
    docker:
      - image: tomaka/cargo-apk
    steps:
      - checkout
      - run: rustup show
      - run: cargo apk build

  deploy:
    docker:
      - image: tomaka/cargo-apk
    steps:
      - checkout
      - run: rustup show
      - run: git clone --depth=1 https://github.com/ozkriff/zemeroth_assets assets
      - run: cargo apk build
      - run: ./.circleci/upload_apk_to_github_releases.sh

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build:
          filters:
            tags:
              ignore: /.*/
      - deploy:
          filters:
            tags:
              only: /.*/
            branches:
              ignore: /.*/
