[package]
name = "futures-util"
version = "0.2.0-beta"
authors = ["Alex Crichton <alex@alexcrichton.com>"]
license = "MIT/Apache-2.0"
repository = "https://github.com/rust-lang-nursery/futures-rs"
homepage = "https://github.com/rust-lang-nursery/futures-rs"
documentation = "https://docs.rs/futures-core"
description = """
Common utilities and extension traits for the futures-rs library.
"""

[features]
std = ["futures-core/std", "futures-io/std", "futures-sink/std", "either/use_std"]
default = ["std", "futures-core/either"]

[dependencies]
futures-core = { path = "../futures-core", version = "0.2.0-beta", default-features = false }
futures-channel = { path = "../futures-channel", version = "0.2.0-beta", default-features = false }
futures-io = { path = "../futures-io", version = "0.2.0-beta", default-features = false }
futures-sink = { path = "../futures-sink", version = "0.2.0-beta", default-features = false}
either = { version = "1.4", default-features = false }

[dev-dependencies]
futures = { path = "../futures", version = "0.2.0-beta" }
futures-executor = { path = "../futures-executor", version = "0.2.0-beta" }
futures-channel = { path = "../futures-channel", version = "0.2.0-beta" }
