[package]
name = "whirlpool"
version = "0.7.0"
authors = ["RustCrypto Developers"]
license = "MIT/Apache-2.0"
description = "Whirlpool hash function"
documentation = "https://docs.rs/whirlpool"
repository = "https://github.com/RustCrypto/hashes"
keywords = ["crypto", "whirlpool", "hash", "digest"]
categories = ["cryptography", "no-std"]

[dependencies]
digest = "0.7"
byte-tools = "0.2"
block-buffer = "0.3"
whirlpool-asm = {version="0.3", optional=true}

[dev-dependencies]
digest = { version = "^0.7.1", features = ["dev"] }

[features]
asm = ["whirlpool-asm"]

[badges]
travis-ci = { repository = "RustCrypto/hashes" }
