[package]
name = "stress2"
version = "0.1.0"
authors = ["Tyler Neely <t@jujit.su>"]
publish = false

[profile.release]
debug = 2

[dependencies]
serde = "1.0"
serde_derive = "1.0"
docopt = "0.8"
chan-signal = "0.3"
rand = "0.4"
sled = { path = "../../crates/sled" }
