[package]
name = "sha3"
version = "0.7.3"
authors = ["RustCrypto Developers"]
license = "MIT/Apache-2.0"
description = "SHA-3 (Keccak) hash function"
documentation = "https://docs.rs/sha3"
repository = "https://github.com/RustCrypto/hashes"
keywords = ["crypto", "sha3", "keccak", "hash", "digest"]
categories = ["cryptography", "no-std"]

[dependencies]
digest = "0.7"
byte-tools = "0.2"
block-buffer = "^0.3.3"
keccak = "0.1"

[dev-dependencies]
digest = { version = "^0.7.1", features = ["dev"] }

[badges]
travis-ci = { repository = "RustCrypto/hashes" }
