[package]
name = "md-5"
version = "0.7.0"
authors = ["RustCrypto Developers"]
license = "MIT/Apache-2.0"
description = "MD5 hash function"
documentation = "https://docs.rs/md-5"
repository = "https://github.com/RustCrypto/hashes"
keywords = ["crypto", "md5", "hash", "digest"]
categories = ["cryptography", "no-std"]

[lib]
name = "md5"

[dependencies]
digest = "0.7"
byte-tools = "0.2"
block-buffer = "0.3"
md5-asm = { version = "0.4", optional=true}

[dev-dependencies]
digest = { version = "^0.7.1", features = ["dev"] }

[features]
asm = ["md5-asm"]

[badges]
travis-ci = { repository = "RustCrypto/hashes" }
